// <auto-generated />
namespace Recruitment_Collaboration_Tool_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletingSkillsetFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletingSkillsetFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201711022220347_deletingSkillsetFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
